#pragma once

#include "Part01.h"
#include "Part02.h"
#include "Part03.h"
#include "Part04.h"
#include "Part05.h"
#include "Part06.h"
#include "Part07.h"
#include "Part08.h"
#include "Part09.h"
#include "Part10.h"
#include "Part11.h"
#include "Part12.h"
#include "Part13.h"